apiVersion: v1
kind: Service
metadata:
  name: wealthflow-frontend-service
  labels:
    app.kubernetes.io/name: wealthflow-frontend
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wealthflow-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
